### ISSUE TITLE
This project is amazing, I think it deserves a tagged release.

### ISSUE THREAD

**Issue by ryanpcmcquen** [trepmal/export-one-post#2]
This program has made my life so much easier, I think it is more than worthy of a 1.0.0 release.  :-)

**Comment by trepmal** [comment]
Thanks :) Tagged v1 (finally...)

**Comment by ryanpcmcquen** [comment]
Woohoo! :tada:

**Comment by ryanpcmcquen** [comment]
Oh, and it DEFINITELY works on custom posts, so if you want to update the README. :+1:
