### ISSUE TITLE
Custom Post Types

### ISSUE THREAD

**Issue by atwellpub** [trepmal/export-one-post#5]
Heya, passing through looking for a solution for a custom post type single item xml export. Does this plugin account for custom post types?

**Comment by trepmal** [comment]
Yes, as per the readme, it works for posts, pages, and custom post types

**Comment by atwellpub** [comment]
amazing I missed that. I could of sworn I briefed the readme before I opened the issue. Very sorry about that and thanks for responding. Thanks again.

**Comment by trepmal** [comment]
No problem (sorry I came off a bit blunt... )
